; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "EX-Installer"
#define MyAppVersion "0.0.20"
#define MyAppPublisher "DCC-EX"
#define MyAppURL "https://dcc-ex.com"
#define MyAppExeName "launch_ex_installer.bat"

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{D2F27D1F-526B-43FD-95A9-C210A82AC7CF}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={autopf}\{#MyAppName}
DisableDirPage=yes
DisableProgramGroupPage=yes
; Uncomment the following line to run in non administrative install mode (install for current user only).
;PrivilegesRequired=lowest
OutputBaseFilename="EX-Installer-Setup-Win64"
SolidCompression=yes
WizardStyle=modern
SetupIconFile=ex_installer\images\dccex.ico
OutputDir=dist
ArchitecturesInstallIn64BitMode=x64
UninstallFilesDir="{app}\__pycache__"

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "launch_ex_installer.bat"; DestDir: "{app}"; Flags: ignoreversion
Source: "python\*"; DestDir: "{app}\python"; Flags: recursesubdirs
Source: "ex_installer\*"; DestDir: "{app}\ex_installer"; Flags: recursesubdirs Excludes: "__pycache__"
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: shellexec postinstall skipifsilent

