/**
 * Starter config file templates — shipped with EX-Installer and used as a fallback
 * when no config file exists on disk and no example file is found in the cloned repo.
 *
 * Each key is the repo folder name (matching the product's repoName after the '/').
 * Inner keys are the config file names (matching minimumConfigFiles / otherConfigFilePatterns).
 *
 * These are intentionally minimal / "clean" generated configs rather than the large
 * commented example files found in the repos — they are ready-to-compile defaults that
 * can be further edited by the user.
 *
 * Keep this file free of Node.js / browser-only dependencies so it is safe to import
 * from every process (main, preload, renderer).
 */

export const STARTER_TEMPLATES: Record<string, Record<string, string>> = {
    /**
     * EX-CommandStation — minimal generated config suitable for an EX-CSB1
     * (ESP32-S3, EXCSB1 motor driver, built-in SH1106 OLED, WiFi AP mode).
     *
     * Matches the output of generateCommandStationConfig() with these defaults:
     *   motorDriver:   'EXCSB1'
     *   display:       'OLED_132x64'  (SH1106 onboard)
     *   enableWifi:    true           (auto for ESP32)
     *   wifiMode:      'ap'
     *   wifiHostname:  'dccex'
     *   wifiChannel:   1
     *   disableEeprom: true           (auto for ESP32)
     *
     * NOTE: IP_PORT, SCROLLMODE, WIFI_HOSTNAME, and OLED_DRIVER are always required —
     *       omitting any of them from a hand-edited config.h will cause a compile error.
     */
    'CommandStation-EX': {
        'config.h': `// config.h - Generated by EX-Installer

#define IP_PORT 2560
#define SCROLLMODE 1

#define MOTOR_SHIELD_TYPE EXCSB1
#define OLED_DRIVER 132,64
#define WIFI_HOSTNAME "dccex"
#define WIFI_SSID "Your network name"
#define WIFI_PASSWORD "Your network passwd"
#define ENABLE_WIFI true
#define WIFI_CHANNEL 1
#define DISABLE_EEPROM
`,
    },

    /**
     * EX-IOExpander — mirrors myConfig.example.h from the DCC-EX repo.
     */
    'EX-IOExpander': {
        'myConfig.h': `/*
 *  © 2022 Peter Cole. All rights reserved.
 *
 *  This is the example configuration file for EX-IOExpander.
 *
 *  It is highly recommended to copy this to "myConfig.h" and modify to suit your
 *  specific requirements.
 *
 *  NOTE: Modifications to this file will be overwritten by future software updates.
 */
#ifndef MYCONFIG_H
#define MYCONFIG_H

/////////////////////////////////////////////////////////////////////////////////////
//  Define I2C address
//  Default 0x65, can be any valid, available I2C address
//
#define I2C_ADDRESS 0x65

/////////////////////////////////////////////////////////////////////////////////////
//  Uncomment to enable diag output
//
// #define DIAG

/////////////////////////////////////////////////////////////////////////////////////
//  Delay between dumping the status of the port config if DIAG enabled
//
#define DIAG_CONFIG_DELAY 5

/////////////////////////////////////////////////////////////////////////////////////
//  Enable test mode - ensure only one test mode is active at one time.
//
// #define TEST_MODE ANALOGUE_TEST
// #define TEST_MODE INPUT_TEST
// #define TEST_MODE OUTPUT_TEST
// #define TEST_MODE PULLUP_TEST

/////////////////////////////////////////////////////////////////////////////////////
//  Uncomment to disable internal I2C pullup resistors
//
// #define DISABLE_I2C_PULLUPS

#endif
`,
    },

    /**
     * EX-Turntable — mirrors config.example.h from the DCC-EX repo.
     */
    'EX-Turntable': {
        'config.h': `/*
 *  © 2022 Peter Cole
 *
 *  This is the configuration file for Turntable-EX.
 */

/////////////////////////////////////////////////////////////////////////////////////
//  Define a valid (and free) I2C address, 0x60 is the default.
//
#define I2C_ADDRESS 0x60

/////////////////////////////////////////////////////////////////////////////////////
//  Define the mode for Turntable-EX.
//  TURNTABLE : 360 degree rotation turntable (default).
//  TRAVERSER : Vertical or horizontal traversers, or limited-rotation turntables.
//
#define TURNTABLE_EX_MODE TURNTABLE
// #define TURNTABLE_EX_MODE TRAVERSER

/////////////////////////////////////////////////////////////////////////////////////
//  Sensor active states.
//
#define HOME_SENSOR_ACTIVE_STATE LOW
#define LIMIT_SENSOR_ACTIVE_STATE LOW
#define RELAY_ACTIVE_STATE HIGH

/////////////////////////////////////////////////////////////////////////////////////
//  Phase switching.
//
#define PHASE_SWITCHING AUTO
#define PHASE_SWITCH_ANGLE 45

/////////////////////////////////////////////////////////////////////////////////////
//  Stepper driver selection.
//
#define STEPPER_DRIVER ULN2003_HALF_CW
// #define STEPPER_DRIVER A4988

/////////////////////////////////////////////////////////////////////////////////////
//  Stepper configuration.
//
#define DISABLE_OUTPUTS_IDLE
#define STEPPER_MAX_SPEED 200
#define STEPPER_ACCELERATION 25
#define STEPPER_GEARING_FACTOR 1

/////////////////////////////////////////////////////////////////////////////////////
//  LED blink rates (milliseconds).
//
#define LED_FAST 100
#define LED_SLOW 500

/////////////////////////////////////////////////////////////////////////////////////
//  Advanced options (uncomment only if needed).
//
// #define DEBUG
// #define SANITY_STEPS 10000
// #define HOME_SENSITIVITY 300
// #define FULL_STEP_COUNT 4096
// #define DEBOUNCE_DELAY 10
`,
    },
}
