; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "EX-Installer"
#define MyAppVersion "0.0.21"
#define MyAppPublisher "DCC-EX"
#define MyAppURL "https://dcc-ex.com"
#define MyModuleName "ex_installer"
#define MyIconFile "ex_installer\images\dccex.ico"
#define MyPython "python\pythonw.exe"
#define MyLicenseFile "LICENSE"
#define MyDCCEXLogo "ex_installer\images\dccex-logo.bmp"
#define MyImg "..\ex_installer\images"

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{D2F27D1F-526B-43FD-95A9-C210A82AC7CF}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={autopf}\{#MyAppName}
DefaultGroupName={#MyAppPublisher}
DisableDirPage=auto
DisableProgramGroupPage=auto
; Uncomment the following line to run in non administrative install mode (install for current user only).
;PrivilegesRequired=lowest
OutputBaseFilename="EX-Installer-Setup-Win64"
SolidCompression=yes
WizardStyle=modern
WizardImageFile="..\{#MyDCCEXLogo}"
WizardImageStretch=no
WizardSmallImageFile="{#MyImg}\dccex-58.bmp,{#MyImg}\dccex-71.bmp,{#MyImg}\dccex-85.bmp,{#MyImg}\dccex-103.bmp,{#MyImg}\dccex-112.bmp,{#MyImg}\dccex-129.bmp,{#MyImg}\dccex-147.bmp"
SetupIconFile="..\{#MyIconFile}"
OutputDir="..\dist"
ArchitecturesAllowed=x64compatible
ArchitecturesInstallIn64BitMode=x64compatible
LicenseFile="..\{#MyLicenseFile}"

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"

[Files]
Source: "..\python\*"; DestDir: "{app}\python"; Flags: recursesubdirs
Source: "..\{#MyModuleName}\*"; DestDir: "{app}\{#MyModuleName}"; Flags: recursesubdirs; Excludes: "__pycache__"
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{group}\{#MyAppName}"; Filename: "{app}\{#MyPython}"; WorkingDir: "{app}"; Parameters: "-m {#MyModuleName}"; IconFilename: "{app}\{#MyIconFile}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyPython}"; WorkingDir: "{app}"; Parameters: "-m {#MyModuleName}"; IconFilename: "{app}\{#MyIconFile}"

[Run]
Filename: "{app}\{#MyPython}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; WorkingDir: "{app}"; Parameters: "-m {#MyModuleName}"; Flags: shellexec postinstall skipifsilent
